### ISSUE TITLE
How vram required? Run in rtx 3060 12gb?

### ISSUE THREAD

**Issue by Koorvux** [MooreThreads/Moore-AnimateAnyone#3]

**Comment by patrolli** [comment]
The VRAM size is up to the resolution. It requires about 15GB to generate a video with resolution of 512x768. You can reduce the resolution to lower VRAM usage.

**Comment by lixunsong** [comment]
The VRAM size is up to the resolution. It requires about 15GB to generate a video with resolution of 512x768. You can reduce the resolution to lower VRAM usage.

**Comment by wikidude** [comment]
That is weird because my OOM error states it tried to allocate 56GB for the example script with -W 512 -H 784 -L 64

`torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 56.27 GiB. GPU 0 has a total capacity of 23.98 GiB of which 14.46 GiB is free. Of the allocated memory 8.76 GiB is allocated by PyTorch, and 408.65 MiB is reserved by PyTorch but unallocated.`

**Comment by John-WL** [comment]
If you have enough ram, it will still work with your 12 Gb card. 
I have 10 Gb of vram and the rest is offloaded to my ram, works fine.

**Comment by fenghe12** [comment]
if you’re trainging it,you may need more than 52GB vram
